### ISSUE TITLE
Bump custom dump dep to 1.0.0

### ISSUE THREAD

**Issue by CyonAlexRDX** [davdroman/XCTJSONKit#13]
Hey David! Hope you are well!

TCAs later version uses `swift-custom-dump` version `1.0.0`, maybe you can bump the version here in swift-json-testing so we dont have clashing versions when using both!

https://github.com/pointfreeco/swift-composable-architecture/blob/main/Package.swift#L26

**Comment by davdroman** [comment]
Hey Alex, hope you’re well too.

I did this a couple weeks ago, if you update to [0.2.0](https://github.com/davdroman/swift-json-testing/releases/tag/0.2.0) you should be all good.

**Comment by CyonAlexRDX** [comment]
@davdroman indeed you did! :D nevermind me! Thx!
